services:
  - type: web
    name: greatgoals-lifestyle-mlm
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 5000
